/**
 * Seed data for K9 Studio (spec §9, §10, §12, §21).
 * All prices are examples and configurable from the admin panel — no code
 * changes are needed for ordinary business updates.
 */

export const TIER_PRESETS = {
  website: [
    {
      tier: "basic",
      name: "Basic",
      priceDelta: 0,
      priceDeltaMmk: 0,
      deliveryDays: 7,
      description: "A clean, fast single-page site that gets your idea online.",
      features: [
        "One-page responsive design",
        "Mobile-first layout",
        "Contact section",
        "Basic SEO setup",
        "1 revision round",
        "Delivery ~7 days",
      ],
      defaults: true,
    },
    {
      tier: "standard",
      name: "Standard",
      priceDelta: 2.38,
      priceDeltaMmk: 10000,
      deliveryDays: 14,
      description: "A complete multi-page site with more polish and features.",
      features: [
        "Up to 5 pages",
        "Custom design system",
        "Smooth scroll animations",
        "Contact form + map",
        "On-page SEO + analytics",
        "2 revision rounds",
        "Delivery ~14 days",
      ],
      defaults: false,
    },
    {
      tier: "premium",
      name: "Premium",
      priceDelta: 4.76,
      priceDeltaMmk: 20000,
      deliveryDays: 21,
      description: "The full K9 experience — motion, 3D and priority handling.",
      features: [
        "Up to 10 pages",
        "Bespoke art direction",
        "3D / WebGL hero or motion sequences",
        "CMS or admin-editable content",
        "Performance + accessibility audit",
        "Priority handling",
        "3 revision rounds",
        "Delivery ~21 days",
      ],
      defaults: false,
    },
  ],
  bot: [
    {
      tier: "basic",
      name: "Basic",
      priceDelta: 0,
      priceDeltaMmk: 0,
      deliveryDays: 5,
      description: "A reliable bot with the essential commands for your community.",
      features: [
        "Telegram or Discord",
        "Up to 8 commands",
        "Simple moderation",
        "Basic welcome/role messages",
        "Hosting guidance",
        "1 revision round",
        "Delivery ~5 days",
      ],
      defaults: true,
    },
    {
      tier: "standard",
      name: "Standard",
      priceDelta: 2.38,
      priceDeltaMmk: 10000,
      deliveryDays: 10,
      description: "A fuller bot with database, scheduling and dashboards.",
      features: [
        "Up to 20 commands",
        "Database storage",
        "Scheduled tasks",
        "Admin panel (simple)",
        "Payment or shop hooks",
        "2 revision rounds",
        "Delivery ~10 days",
      ],
      defaults: false,
    },
    {
      tier: "premium",
      name: "Premium",
      priceDelta: 4.76,
      priceDeltaMmk: 20000,
      deliveryDays: 18,
      description: "Production-grade bot with advanced workflows and priority support.",
      features: [
        "Unlimited commands",
        "Web dashboard",
        "Advanced workflows + webhooks",
        "Multi-language responses",
        "Anti-abuse systems",
        "Priority handling",
        "3 revision rounds",
        "Delivery ~18 days",
      ],
      defaults: false,
    },
  ],
  aiBot: [
    {
      tier: "basic",
      name: "Basic",
      priceDelta: 0,
      priceDeltaMmk: 0,
      deliveryDays: 6,
      description: "An AI assistant on Telegram with your own instructions.",
      features: [
        "Telegram AI bot",
        "Custom role + instructions",
        "Context memory within a chat",
        "1 revision round",
        "Delivery ~6 days",
      ],
      defaults: true,
    },
    {
      tier: "standard",
      name: "Standard",
      priceDelta: 3.57,
      priceDeltaMmk: 15000,
      deliveryDays: 12,
      description: "Smarter context, custom knowledge and workflow actions.",
      features: [
        "Custom knowledge base",
        "Group + private chat modes",
        "Usage limits / quota controls",
        "Simple admin commands",
        "2 revision rounds",
        "Delivery ~12 days",
      ],
      defaults: false,
    },
    {
      tier: "premium",
      name: "Premium",
      priceDelta: 7.14,
      priceDeltaMmk: 30000,
      deliveryDays: 20,
      description: "A full AI workflow agent with integrations and priority handling.",
      features: [
        "Tool use / API integrations",
        "Multi-step AI workflows",
        "Analytics on conversations",
        "Voice message replies",
        "Priority handling",
        "3 revision rounds",
        "Delivery ~20 days",
      ],
      defaults: false,
    },
  ],
};

export const CATALOG_SEED = [
  // ─── SERVICES ───────────────────────────────────────────────────────────
  {
    kind: "service",
    slug: "website-development",
    category: "Website Development",
    name: "Website Development",
    tagline: "From a sharp landing page to a full web application.",
    description:
      "We design and build websites that feel intentional — landing pages, business sites, portfolios, personal sites and full web applications.",
    longDescription:
      "Every website starts with your goal: sell something, explain something, or look unforgettable while doing it. We handle design, build, deployment and the technical decisions — you describe the outcome you want. Domains and hosting costs are billed separately at cost where applicable.",
    pricingModel: "tiered",
    basePriceUsd: 9.52,
    basePriceMmk: 40000,
    featured: true,
    status: "active",
    order: 1,
    icon: "globe",
    highlights: [
      "Design + build + deployment included",
      "Mobile-first and fast",
      "You describe the outcome — we handle the tech",
    ],
    audience: ["Small businesses", "Creators", "Anyone with an idea"],
    included: [
      "Design and development",
      "Responsive across devices",
      "Deployment to your host",
      "Handover walkthrough",
    ],
    deliveryNote: "Timelines depend on the chosen package. Domain and third-party costs are additional at cost.",
    requirements: [
      "Your goal in one or two sentences",
      "Any references you like (optional)",
      "Text/images you want on the site (optional to start)",
    ],
    faq: [
      { q: "Do I need technical knowledge?", a: "No. Describe what you want in plain language — we translate it into the technical plan." },
      { q: "What about domain and hosting?", a: "Those are third-party costs, billed separately at actual cost. We set everything up for you." },
      { q: "Can I upgrade my package later?", a: "Yes — packages can be upgraded any time; you only pay the difference." },
    ],
    tiers: TIER_PRESETS.website,
  },
  {
    kind: "service",
    slug: "bot-creation",
    category: "Bot Creation",
    name: "Bot Creation",
    tagline: "Telegram & Discord bots that do real work.",
    description:
      "Game bots, shopping bots, community bots, utility bots — built for Telegram and Discord, configured around what your community needs.",
    longDescription:
      "Bots are software with a personality. Tell us what your community or shop needs — moderating, selling, playing, reminding — and we build, host and hand over a bot that does it. You get the bot, the keys, and a walkthrough.",
    pricingModel: "tiered",
    basePriceUsd: 7.14,
    basePriceMmk: 30000,
    featured: true,
    status: "active",
    order: 2,
    icon: "bot",
    highlights: [
      "Telegram & Discord",
      "Commands, moderation, shops, games",
      "You own the bot and its keys",
    ],
    audience: ["Communities", "Online sellers", "Gamers"],
    included: ["Bot development", "Setup and deployment", "Hosting guidance", "Handover walkthrough"],
    deliveryNote: "Timelines depend on the chosen package.",
    requirements: ["What the bot should do", "Where it will run (Telegram/Discord)", "Who will use it"],
    faq: [
      { q: "Which platforms do you support?", a: "Telegram and Discord at launch. Other platforms on request via a custom project." },
      { q: "Who pays for hosting?", a: "Simple bots run free tiers. Heavy bots may need small hosting costs — we advise before you commit." },
    ],
    tiers: TIER_PRESETS.bot,
  },
  {
    kind: "service",
    slug: "ai-bots",
    category: "AI Bots",
    name: "AI Bots",
    tagline: "AI assistants with your rules, your knowledge, your style.",
    description:
      "Telegram AI assistants with custom roles, context and behavior — more than a bot: an assistant that understands your world.",
    longDescription:
      "AI bots sit above normal bots in what they can do. Give it a role — shop assistant, community helper, study tutor, character — feed it your context and rules, and it answers, guides and acts. We configure the model, the memory and the guardrails.",
    pricingModel: "tiered",
    basePriceUsd: 11.9,
    basePriceMmk: 50000,
    featured: true,
    status: "active",
    order: 3,
    icon: "sparkles",
    highlights: [
      "Custom role & instructions",
      "Context and knowledge base",
      "AI-powered workflows",
    ],
    audience: ["Anyone who wants an AI helper"],
    included: ["AI configuration", "Prompt & role design", "Deployment to Telegram", "Usage walkthrough"],
    deliveryNote: "AI API usage costs are paid by the customer at cost, or through a K9-managed plan.",
    requirements: ["The role your AI should play", "Sample questions it should handle", "Tone / style preferences"],
    faq: [
      { q: "How is an AI bot different from a normal bot?", a: "Normal bots follow fixed commands. AI bots understand language and context — they can hold conversations and make judgment calls within your rules." },
      { q: "What about AI usage costs?", a: "AI providers charge per usage. We'll recommend a plan that fits your traffic — costs pass through at cost." },
    ],
    tiers: TIER_PRESETS.aiBot,
  },
  {
    kind: "service",
    slug: "custom-projects",
    category: "Custom Projects",
    name: "Custom Projects",
    tagline: "If you can describe it, we can scope it.",
    description:
      "Surprise projects, personalized experiences, unusual websites and unique digital solutions — scoped together from your description.",
    longDescription:
      "Custom projects start as a conversation. Describe your idea in plain language — a gift experience, an interactive invitation, a strange and wonderful web toy, a tool nobody has built yet. We reply with a scope, a price and a timeline, then build it.",
    pricingModel: "fixed",
    basePriceUsd: 23.81,
    basePriceMmk: 100000,
    featured: true,
    status: "active",
    order: 4,
    icon: "wand",
    highlights: [
      "Plain-language descriptions are enough",
      "Scoped before you pay",
      "One idea, one build",
    ],
    audience: ["People with custom ideas"],
    included: ["Scoping conversation", "Proposal with fixed price", "Build and delivery", "Handover"],
    deliveryNote: "Quoted per project after scoping — the listed price is a starting point.",
    requirements: ["Your idea in a few sentences", "Any references or inspiration", "Budget and deadline if known"],
  },
  // ─── PRODUCTS ───────────────────────────────────────────────────────────
  {
    kind: "product",
    slug: "cinematic-photo-prompts",
    category: "Prompts",
    name: "Cinematic Photo Prompt Pack",
    tagline: "40 context-rich prompts for photo-realistic AI images.",
    description:
      "A pack of 40 production-grade photo prompts with full context blocks — camera, lighting, mood, subject and style — that AI systems actually follow.",
    longDescription:
      "Most prompts fail because they're vague. Each prompt in this pack is a structured instruction: subject, environment, camera language, lighting, color grade and constraints. Works with Midjourney, Flux, Stable Diffusion and similar systems.",
    pricingModel: "fixed",
    basePriceUsd: 2.38,
    basePriceMmk: 10000,
    featured: true,
    status: "active",
    order: 1,
    icon: "camera",
    highlights: ["40 structured prompts", "Context-first design", "Works across AI image tools"],
    audience: ["Creators", "Designers", "AI enthusiasts"],
    included: ["40 prompts in a copy-ready file", "Usage tips per prompt", "Free minor updates"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-cinematic-photo-prompts.pdf", kind: "pdf" }],
  },
  {
    kind: "product",
    slug: "video-prompt-pack",
    category: "Prompts",
    name: "Video Prompt Pack",
    tagline: "Motion-ready prompts for AI video generation.",
    description:
      "Structured prompts for AI video tools — scene, camera movement, pacing, lighting and continuity notes included.",
    longDescription:
      "Video prompts need choreography. This pack includes shot-by-shot structure: subject motion, camera movement, transitions and timing — written for current AI video models.",
    pricingModel: "fixed",
    basePriceUsd: 3.57,
    basePriceMmk: 15000,
    featured: false,
    status: "active",
    order: 2,
    icon: "film",
    highlights: ["Scene + camera structure", "Continuity notes", "Copy-ready"],
    audience: ["Content creators"],
    included: ["30 video prompts", "Shot-structure cheat sheet"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-video-prompt-pack.pdf", kind: "pdf" }],
  },
  {
    kind: "product",
    slug: "ai-role-library",
    category: "AI Role Prompts",
    name: "AI Role Library",
    tagline: "12 specialist roles that make AI dramatically better at its job.",
    description:
      "Developer, designer, researcher, editor, strategist and more — complete instruction systems with behavior rules, output formats and edge-case handling.",
    longDescription:
      "A role prompt is an operating manual for an AI. Each of the 12 roles in this library defines expertise, behavior rules, output formats, quality checks and refusal boundaries — so the AI performs like a specialist instead of a generalist.",
    pricingModel: "fixed",
    basePriceUsd: 4.76,
    basePriceMmk: 20000,
    featured: true,
    status: "active",
    order: 3,
    icon: "brain",
    highlights: ["12 complete role systems", "Behavior + output rules", "Edge-case handling"],
    audience: ["Developers", "Founders", "Students", "Researchers"],
    included: ["12 role prompts", "How-to-customize guide", "Free minor updates"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-ai-role-library.pdf", kind: "pdf" }],
  },
  {
    kind: "product",
    slug: "glass-ui-kit",
    category: "Code",
    name: "Glass UI Kit — CSS Components",
    tagline: "The glass component CSS used on this very website.",
    description:
      "Copy-paste CSS components: glass cards, glow buttons, tier switchers, badges and focus states — the same system powering K9 Studio.",
    longDescription:
      "A compact, dependency-free CSS file with our glass surface system, violet glow accents, buttons, cards, badges and focus-visible states. Includes light-mode tokens and reduced-motion handling.",
    pricingModel: "fixed",
    basePriceUsd: 3.57,
    basePriceMmk: 15000,
    featured: false,
    status: "active",
    order: 4,
    icon: "code",
    highlights: ["Dependency-free CSS", "Same system as this site", "Light + dark tokens"],
    audience: ["Developers", "Design engineers"],
    included: ["CSS file", "HTML examples", "Token reference"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-glass-ui-kit.zip", kind: "zip" }],
  },
  {
    kind: "product",
    slug: "css-animations-pack",
    category: "Code",
    name: "CSS Animation Pack",
    tagline: "30 tasteful animations — reveals, glows, hover physics.",
    description:
      "30 copy-paste CSS animations: scroll reveals, magnetic hovers, glow pulses, text shimmers and page transitions with reduced-motion variants.",
    longDescription:
      "Animations that feel premium, not busy. Each animation ships with a CSS block, an HTML snippet, and a prefers-reduced-motion variant. No JavaScript required.",
    pricingModel: "fixed",
    basePriceUsd: 2.38,
    basePriceMmk: 10000,
    featured: false,
    status: "active",
    order: 5,
    icon: "zap",
    highlights: ["30 animations", "Reduced-motion variants", "Zero JS"],
    audience: ["Developers", "Students"],
    included: ["CSS + HTML examples", "Usage guide"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-css-animations.zip", kind: "zip" }],
  },
  {
    kind: "product",
    slug: "dev-website-prompt-system",
    category: "Prompts",
    name: "Website Development Prompt System",
    tagline: "Turn plain ideas into complete website specs — with AI.",
    description:
      "A structured prompt system that interviews you about your website idea and produces a full build spec: pages, sections, content, and tech choices.",
    longDescription:
      "Built from K9's own intake flow: the system asks the right questions (audience, goal, pages, tone, references), then outputs a structured specification a developer — or an AI — can build from directly.",
    pricingModel: "fixed",
    basePriceUsd: 4.76,
    basePriceMmk: 20000,
    featured: false,
    status: "active",
    order: 6,
    icon: "layout",
    highlights: ["Interview → spec flow", "Dev-ready output", "Reusable system"],
    audience: ["Founders", "Freelancers", "Agencies"],
    included: ["Main system prompt", "Follow-up question set", "Spec template"],
    deliveryNote: "Instant download after purchase.",
    downloadable: [{ title: "k9-website-prompt-system.pdf", kind: "pdf" }],
  },
];

export const SETTINGS_SEED = [
  { key: "mmkPerUsd", value: 4200 },
  { key: "supportTelegram", value: "https://t.me/k9studio" },
  { key: "telegramChannel", value: "https://t.me/k9studio" },
  { key: "announcement", value: "K9 Credit now accepted on every service and product." },
];

export const PROJECTS_SEED = [
  {
    slug: "paywell",
    name: "PayWell",
    category: "Payments Platform",
    period: "Active — ongoing",
    summary:
      "Payment orchestration for local wallets — one interface over KBZPay, WavePay, AYA and more.",
    role: "Design · Development · Integrations",
    stack: ["Web", "Payment integrations", "Merchant tools"],
    overview:
      "PayWell lets merchants accept payments through Myanmar's local wallets without wiring each API by hand. K9 Studio designed the merchant experience and built the integration layer that normalizes every wallet behind a single flow.",
    problem:
      "Merchants had to integrate each wallet separately — different dashboards, different APIs, different failure modes — and small sellers simply couldn't.",
    goal:
      "One clean interface where a seller connects a wallet, shares a payment link, and sees every transaction in one place.",
    solution:
      "A merchant web app with wallet adapters, a unified transaction ledger, payment links and clear settlement views — designed so a first-time seller can go from signup to first payment in minutes.",
    features: [
      "Unified merchant dashboard",
      "Wallet adapters (KBZPay, WavePay, AYA)",
      "Payment links and QR flows",
      "Transaction ledger with status",
      "Settlement summaries",
    ],
    status: "In production — actively developed with K9 Studio",
    liveUrl: "https://paywell.example",
  },
  {
    slug: "k9-studio-platform",
    name: "K9 Studio Platform",
    category: "Digital Studio Platform",
    period: "Active — this website",
    summary:
      "The platform you're using right now: catalog, K9 Credit ledger, instant checkout and order tracking.",
    role: "Product · Design · Engineering",
    stack: ["React", "Convex", "TypeScript", "Telegram API"],
    overview:
      "K9 Studio runs on its own platform — a catalog-driven storefront where services and products are data, purchases settle instantly through K9 Credit, and every order notifies the studio over Telegram.",
    problem:
      "Freelance studios drown in scattered chats and manual price lists; customers can't see what things cost or where their order stands.",
    goal:
      "A self-serve studio: browse, configure a package, pay instantly, and track progress — with the studio reachable on Telegram.",
    solution:
      "This platform: a structured catalog with tiered packages, an auditable credit ledger, instant checkout, a manual order fallback, and an admin surface for the whole business.",
    features: [
      "Catalog-driven services & products",
      "Basic / Standard / Premium packages",
      "K9 Credit with auditable ledger",
      "Instant purchase + manual fallback",
      "Order tracking and Telegram notifications",
    ],
    status: "In production — you're using it",
  },
];
